services:
  - type: web
    name: dicss
    env: python
    plan: free
    autoDeploy: true
    buildCommand: pip install -r requirements-prod.txt
    startCommand: sh render-start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: SECRET_KEY
        generateValue: true
